// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","id":"1"},"2":{"path":"/register","id":"2"},"3":{"path":"/universities","id":"3"},"4":{"path":"/student","id":"4"},"5":{"path":"/student/applications","id":"5"},"6":{"path":"/student/application-form","id":"6"},"7":{"path":"/admin","access":"admin","id":"7"},"8":{"path":"/admin/applications","access":"admin","id":"8"},"9":{"path":"/admin/universities","access":"admin","id":"9"},"10":{"path":"/admin/majors","access":"admin","id":"10"},"11":{"path":"/admin/statistics","access":"admin","id":"11"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Register__index" */'@/pages/Register/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Universities__index" */'@/pages/Universities/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Student__index" */'@/pages/Student/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Student__MyApplications" */'@/pages/Student/MyApplications.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Student__ApplicationForm" */'@/pages/Student/ApplicationForm.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Admin__index" */'@/pages/Admin/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Admin__Applications" */'@/pages/Admin/Applications.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Admin__University__index" */'@/pages/Admin/University/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Admin__Major__index" */'@/pages/Admin/Major/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Admin__Statistics" */'@/pages/Admin/Statistics.tsx')),
},
  };
}
